$(document).ready(function()
{
    function validateEditor() {
        // Revalidate the content when its value is changed by Summernote
        $('#newBlogForm').bootstrapValidator('revalidateField', 'content');
    };

    $('#newBlogForm').bootstrapValidator({
            excluded: [':disabled'],
            live:'enabled',
            submitButtons: 'button[id="blogSubmit"]',
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                title: {
                    validators: {
                        notEmpty: {
                            message: 'The title is required and should be at least 140 characters'
                        }
                    }
                },
                content: {
                    validators: {
                        callback: {
                            message: 'The content is required and cannot be empty',
                            callback: function(value, validator, $field) {
                                var code = $('[name="content"]').code();
                                // <p><br></p> is code generated by Summernote for empty content
                                return (code !== '' && code !== '<p><br></p>' && code.length > 139);
                            }
                        }
                    }
                }
            }
        })
        .find('[name="content"]')
        .summernote({
            height: 400,
            onkeyup: function() {
                validateEditor();
            },
            onpaste: function() {
                validateEditor();
            }
        });

    $('#newBlogForm').submit(function(event)
    {
        /* stop form from submitting normally */
        event.preventDefault();
    });
});

function postBlog()
{
    $('#newBlogForm').data('bootstrapValidator').validate();

    if($('#newBlogForm').data('bootstrapValidator').isValid())
    {
        var title = $('#title').val();
        var content = $('#content').code();

        $.post('http://b2.com/postBlog', {title: title, content: content}, function(response)
        {
            if (response == 'success')
            {
                bootbox.alert("Blog Saved Successfully!", function() {
                    window.location = 'http://b2.com/home'
                });
            }

        });

    }
}

function editBlog()
{
    $('#newBlogForm').data('bootstrapValidator').validate();

    if($('#newBlogForm').data('bootstrapValidator').isValid())
    {
        var title = $('#title').val();
        var content = $('#content').code();
        var id = $('#blogid').val();

        $.post('http://b2.com/posteditBlog', {title: title, content: content, id: id}, function(response)
        {
            if (response == 'Success')
            {
                bootbox.alert("Blog updated Successfully!", function() {
                    window.location = 'http://b2.com/home'
                });
            }

        });

    }
}